import BasicTabs from "@/components/BasicTabs";
import styles from "@/styles/Home.module.css";
import localFont from "next/font/local";
import Head from "next/head";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Material UI tabs list with action buttons using NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <div className={styles.heading}>
            Material UI tabs list with icons or action buttons using NextJS
          </div>
          <div>
            <h1
              style={{
                width: "100%",
                textAlign: "center",
                marginTop: "16px",
                marginBottom: "34px",
                justifyContent: "center",
              }}
            >
              With{" "}
              <span
                style={{
                  background:
                    "linear-gradient(135deg, #ff6b6b, #fbc531, #4cd137, #00a8ff, #9c88ff)",
                  WebkitBackgroundClip: "text",
                  backgroundClip: "text",
                  color: "transparent",
                }}
              >
                Material UI
              </span>
              &nbsp;|&nbsp;
              <Link
                style={{
                  color: "lightpink",
                }}
                target="_blank"
                href={
                  "https://toofancoder.com/blog/material-ui-tab-list-with-icons-or-action-buttons?utm_source=github_sample"
                }
              >
                Visit Blog
              </Link>
            </h1>
          </div>
          <div className={styles.tabContainer}>
            <BasicTabs />
          </div>
        </main>
      </div>
    </>
  );
}
